version: '3.4'
services:
  netbox:
    ports:
      - "28000:8080"
    healthcheck:
      start_period: 120s
      timeout: 5s
      interval: 15s
  netbox-housekeeping:
    healthcheck:
      start_period: 120s
      timeout: 5s
      interval: 15s
  netbox-worker:
    healthcheck:
      start_period: 120s
      timeout: 5s
      interval: 15s
